import PageHero from "@/components/PageHero";

export const metadata = {
  title: "Terms & Conditions — FabricFlow",
  description: "The terms governing your use of the FabricFlow platform.",
};

const SECTIONS = [
  {
    h: "1. Acceptance of terms",
    p: "By registering for or using the FabricFlow platform, you agree to these Terms & Conditions. If you do not agree, you should not use the platform.",
  },
  {
    h: "2. Accounts",
    p: "Buyer accounts are subject to approval by the mother company. You are responsible for maintaining the confidentiality of your login credentials and for all activity under your account. You must provide accurate registration information and keep it up to date.",
  },
  {
    h: "3. Orders and feasibility",
    p: "Feasibility predictions, plant recommendations, production estimates, and timelines provided by the platform are decision-support outputs generated by AI models. They are estimates, not guarantees. Final commitments are confirmed through the order workflow.",
  },
  {
    h: "4. Acceptable use",
    p: "You agree not to misuse the platform, attempt to gain unauthorised access, upload unlawful or infringing content, or interfere with its operation. Uploaded style files must be your own or licensed for your use.",
  },
  {
    h: "5. Intellectual property",
    p: "The platform, its software, and its models remain the property of FabricFlow. Content you upload remains yours; you grant us the limited right to use it to provide the service and fulfil your orders.",
  },
  {
    h: "6. Limitation of liability",
    p: "The platform is provided on an \"as is\" basis. To the maximum extent permitted by law, FabricFlow is not liable for indirect or consequential losses arising from the use of, or reliance on, the platform or its predictions.",
  },
  {
    h: "7. Changes and termination",
    p: "We may update these terms or suspend accounts that breach them. Continued use of the platform after changes take effect constitutes acceptance of the revised terms.",
  },
  {
    h: "8. Contact",
    p: "Questions about these terms can be sent through the Contact Us page.",
  },
];

export default function TermsPage() {
  return (
    <>
      <PageHero
        tone="slate"
        title="Terms & Conditions"
        subtitle={`The terms governing your use of the FabricFlow platform. Last updated ${new Date().getFullYear()}.`}
        crumbs={[{ name: "Terms & Conditions" }]}
      />
    <section className="max-w-3xl mx-auto px-4 sm:px-6 py-16">
      <div className="space-y-8">
        {SECTIONS.map((s) => (
          <div key={s.h}>
            <h2 className="text-lg font-semibold text-slate-900 mb-2">{s.h}</h2>
            <p className="text-slate-600 leading-relaxed">{s.p}</p>
          </div>
        ))}
      </div>
    </section>
    </>
  );
}
